export { createHarshy, harshy, type CreateHarshyDeps, type HarshyClient } from "./client";
export {
  ARCHIVE_INDEX_FILE,
  DEFAULT_ARCHIVE_MAX_ITEMS,
  archiveFileName,
  archiveIndexPayload,
  createIndexedArchive,
  parseArchiveIndex,
  type ArchiveIndex,
  type IndexedArchive,
} from "./indexed-archive";
export {
  createMemoryJsonFileStore,
  createMemoryKeyValue,
  createPrefixedJsonFileStore,
  type JsonFileStore,
  type JsonKeyValue,
} from "./json-file-store";
export {
  archiveSessionExport,
  createSessionArchive,
  parseArchivedSession,
} from "./session-archive";
export { createSimulatedEngine } from "./simulated-engine";
export { formatTripDurationMs, formatTripLiveDisplay } from "./trip-live";
export type {
  ArmWatchOptions,
  DetectorConfig,
  DeviceInfo,
  DrivingEvent,
  DrivingEventType,
  EngineSession,
  HarshEventLevel,
  HarshLevel,
  HarshyClientState,
  HarshyListeners,
  HarshySource,
  HarshyStartOptions,
  ImpactDirection,
  ImuSample,
  LiveMetrics,
  LocationSample,
  NativeStartOptions,
  PermissionResult,
  RecordingMode,
  SensorCapabilities,
  SensorEngine,
  SessionExport,
  TripHeuristicConfig,
  TripLiveDisplayPayload,
  TripMetrics,
  TripTrigger,
  UploadAdapter,
  WatchFix,
  WatchPhase,
  WatchState,
} from "./types";

/**
 * Host integration surface. Detector math stays in `@harshy/core`;
 * hosts should not copy pulse / scoring logic into the app.
 */
export {
  COMPOUND_EVENT_TYPES,
  DEFAULT_DETECTOR_CONFIG,
  DEFAULT_NATIVE_START_OPTIONS,
  DEFAULT_TRIP_HEURISTIC_CONFIG,
  POSSIBLE_IMPACT_TYPE,
  PHONE_HANDHELD_TYPE,
  SCORE_PENALTY_X,
  analyzeTrip,
  compactLocationSample,
  compactSessionExport,
  createTripAnalyzer,
  emptyTripEndState,
  emptyTripStartState,
  endedAtMsWithoutIdleTail,
  eventCounts,
  grantedPermissions,
  harshLevelLabel,
  impactDirectionLabel,
  isLocationGranted,
  isNonAutomotiveActivity,
  isPhoneHandheld,
  isPossibleImpact,
  commitStartConfig,
  locationToWatchFix,
  mergeDetectorConfig,
  mergeNativeStartOptions,
  mergeTripHeuristicConfig,
  parseDetectorConfig,
  parseSessionExport,
  parseTripTrigger,
  permissionLabel,
  permissionResult,
  scoreEvents,
  sessionExportSchema,
  shouldEndTrip,
  shouldStartTrip,
  trimIdleTailSamples,
  warmupEndConfig,
  IDLE_HYSTERESIS_MS,
  MAX_LOCATION_SAMPLES,
  maxImuSamples,
  trimRingBuffer,
} from "@harshy/core";
