export type { Attitude, DetectorConfig, DetectorScoreWeights, DeviceInfo, DrivingEvent, DrivingEventType, HarshEventLevel, HarshLevel, ImpactDirection, ImuSample, LiveMetrics, LocationSample, NativeStartOptions, PermissionResult, PermissionStatus, RecordingMode, SensorCapabilities, SessionExport, TripMetrics, TripTrigger, UploadAdapter, Vec3 } from "./types.js";
export {
  grantedPermissions,
  isLocationGranted,
  permissionLabel,
  permissionResult,
} from "./permissions.js";
export { HARSHY_SDK_VERSION } from "./version.js";
export {
  DEFAULT_DETECTOR_CONFIG,
  DEFAULT_NATIVE_START_OPTIONS,
  SCORE_MAX,
  SCORE_PENALTY_X,
  SCORE_RELATIVE_EXPOSURE_MAX,
  SCORE_RELATIVE_EXPOSURE_MIN,
  SMOOTH_CEILING_X,
  SMOOTH_CORNER_MIN_TURN_DEG,
  SMOOTH_CREDIT_WEIGHT,
  SMOOTH_CREEP_FLOOR_MPS2,
  SMOOTH_CREEP_HOLD_MIN_M,
  SMOOTH_CREEP_HOLD_MS,
  SMOOTH_CREEP_MIN_SPEED_DELTA_MPS,
  SMOOTH_FLOOR_MPS2,
  SMOOTH_GAP_M,
  SMOOTH_HOLD_MIN_M,
  SMOOTH_HOLD_MS,
  HARSH_CORNER_HOLD_MIN_M,
  HARSH_CORNER_HOLD_MS,
  HARSH_CORNER_MIN_TURN_DEG,
  PATH_ONLY_CORNER_MAX_ACCURACY_M,
  PATH_ONLY_LATERAL_MAX_MPS2,
  mergeDetectorConfig,
  mergeNativeStartOptions,
  relativeScore,
  relativeScoreWeight,
} from "./config.js";
export {
  analyzeTrip,
  createTripAnalyzer,
  eventCounts,
  scoreEvents,
  eventScorePoints,
  tripScoreFields,
  isSmoothDrivingEvent,
  scoreExposureScale,
  summarizeTrip,
  type TripAnalyzer,
  type TripAnalyzerOptions,
} from "./detector.js";
export {
  YAW_COURSE_DISAGREE_DEG,
  YAW_GYRO_CONFIRM_MAX_RATIO,
  YAW_GYRO_CONFIRM_RATIO,
  clamp,
  confirmedYawDetail,
  confirmedYawRadps,
  derivedCourseDeg,
  derivedSpeedMps,
  haversineM,
  magnitude,
  mpsToKmh,
  pathBearingDeg,
  severityFromPeak,
  toDeg,
  toRad,
  unwrapDeltaDeg,
  verticalGyroRadps,
  wrapCourseDeg,
} from "./geo.js";
export {
  HEADING_CONFIRM_BAND_DEG,
  HEADING_CONFIRM_SAMPLES,
  HEADING_PUBLISH_DEG,
  HEADING_SMOOTH_TAU_MS,
  advanceHeadingFilter,
  emptyHeadingFilter,
  type HeadingFilter,
} from "./heading.js";
export {
  COMPOUND_EVENT_TYPES,
  isCompoundType,
  tagCompoundOverlaps,
} from "./compound.js";
export {
  DEFAULT_HARSH_HEAVY_X,
  DEFAULT_HARSH_MEDIUM_X,
  HARSH_LEVELS,
  harshEventLevel,
  harshLevel,
  harshLevelLabel,
  harshLevelRank,
  isSwerveMotion,
  liveHarshLevels,
  yawRateJerkRadps2,
  longitudinalHarshLevel,
} from "./harsh.js";
export {
  detectorConfigSchema,
  drivingEventSchema,
  harshEventLevelSchema,
  impactDirectionSchema,
  imuSampleSchema,
  locationSampleSchema,
  parseDetectorConfig,
  parseSessionExport,
  sessionExportSchema,
  tripTriggerSchema,
} from "./schemas.js";
export {
  DEFAULT_TRIP_HEURISTIC_CONFIG,
  emptyTripEndState,
  emptyTripStartState,
  endedAtMsWithoutIdleTail,
  isNonAutomotiveActivity,
  locationToWatchFix,
  commitStartConfig,
  mergeTripHeuristicConfig,
  parseTripTrigger,
  shouldEndTrip,
  shouldStartTrip,
  trimIdleTailSamples,
  warmupEndConfig,
  type MotionActivity,
  type TripEndState,
  type TripHeuristicConfig,
  type TripStartState,
  type WatchFix,
} from "./autoTrip.js";
export {
  assessRoad,
  roadRmsForLocation,
  verticalLinearAccel,
  ROAD_WINDOW_MS,
  type AssessRoadOptions,
} from "./road.js";
export {
  DEFAULT_IMPACT_COOLDOWN_MS,
  DEFAULT_IMPACT_FLOOR_MPS2,
  DEFAULT_IMPACT_FREE_FALL_LOOKBACK_MS,
  DEFAULT_IMPACT_FREE_FALL_MPS2,
  DEFAULT_IMPACT_LOOKAHEAD_MS,
  DEFAULT_IMPACT_PEAK_HIGH_MPS2,
  DEFAULT_IMPACT_PEAK_MPS2,
  DEFAULT_IMPACT_PULSE_MAX_MS,
  DEFAULT_IMPACT_ROLLOVER_DEG,
  DEFAULT_IMPACT_SPEED_DELTA_MPS,
  DEFAULT_IMPACT_VERTICAL_MAX,
  POSSIBLE_IMPACT_TYPE,
  classifyImpactDirection,
  gravityTiltDeg,
  impactDirectionLabel,
  isPossibleImpact,
  sampleLinearAccel,
  verticalShare,
} from "./impact.js";
export {
  DEFAULT_HANDHELD_BASELINE_ALPHA,
  DEFAULT_HANDHELD_CONFIRM_MS,
  DEFAULT_HANDHELD_COOLDOWN_MS,
  DEFAULT_HANDHELD_EXIT_MS,
  DEFAULT_HANDHELD_EXIT_TILT_DEG,
  DEFAULT_HANDHELD_GYRO_RADPS,
  DEFAULT_HANDHELD_MOTION_MPS2,
  DEFAULT_HANDHELD_QUIET_GYRO_RADPS,
  DEFAULT_HANDHELD_QUIET_MOTION_MPS2,
  DEFAULT_HANDHELD_STABLE_MS,
  DEFAULT_HANDHELD_TILT_DEG,
  PHONE_HANDHELD_TYPE,
  emptyHandheldFilter,
  isPhoneHandheld,
} from "./handheld.js";
export {
  generateSampleTrip,
  playSimulatedTrip,
  LIVE_SIM_VARIANTS,
  SIM_TRIP_VARIANTS,
  type PlaybackHandlers,
  type SimTripVariant,
  type SimulatedTrip,
} from "./simulate.js";
export { compactLocationSample, compactSessionExport, stringifySessionExport } from "./session-compact.js";
export { uploadSession } from "./upload.js";
export {
  IDLE_HYSTERESIS_MS,
  IDLE_LOCATION_INTERVAL_MS,
  IDLE_LOCATION_MIN_MOVE_M,
  MAX_IMU_MINUTES,
  MAX_LOCATION_SAMPLES,
  RING_TRIM_SLACK_FRACTION,
  advanceIdleMotion,
  emptyIdleMotionState,
  isIdle,
  maxImuSamples,
  shouldKeepIdleLocation,
  trimRingBuffer,
  type IdleMotionState,
} from "./tripBuffer.js";
export {
  DRIVE_FIX_COARSE_FRACTION_DIGITS,
  DRIVE_FIX_GNSS_ACCURACY_M,
  DRIVE_FIX_ACCEL_MAX_DT_SEC,
  DRIVE_FIX_MAX_ACCEL_MPS2,
  DRIVE_FIX_MAX_SPEED_MPS,
  DRIVE_FIX_SPEED_HOLD_RATIO,
  DRIVE_FIX_MAX_STEP_M,
  DRIVE_FIX_RESET_AFTER,
  DRIVE_FIX_SPIKE_MIN_M,
  DRIVE_FIX_SPIKE_RATIO,
  compensateDrivePath,
  coordinateFractionDigits,
  isCoarseNetworkLikeFix,
  isDrivePathSpike,
  isPlausibleDriveStep,
  isSuspiciousSpeedLeap,
  speedLeapHolds,
  lastLocationAnchor,
  shouldAcceptDriveFix,
  type DriveFixOptions,
  type DriveFixPoint,
} from "./drivePath.js";
